"""миграция 2 - добавлен start_date в WaterConsumptionLog

Revision ID: 2073b7ecf35b
Revises: 747da3b542ca
Create Date: 2025-04-12 18:01:48.496168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2073b7ecf35b'
down_revision: Union[str, None] = '747da3b542ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('water_consumption_log', sa.Column('start_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('water_consumption_log', 'start_date')
    # ### end Alembic commands ###
