"""добавлено год отдельно в wcl_category

Revision ID: 37c30adeb159
Revises: 466d8a2b7d0c
Create Date: 2025-06-16 00:41:24.800719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c30adeb159'
down_revision: Union[str, None] = '466d8a2b7d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wcl_category', sa.Column('year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wcl_category', 'year')
    # ### end Alembic commands ###
