"""миграция 2 - добавлен person_signature в RecordWCL 

Revision ID: 6fb2435775ef
Revises: 199fc77679ff
Create Date: 2025-04-14 20:52:11.750789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb2435775ef'
down_revision: Union[str, None] = '199fc77679ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_wcl', sa.Column('person_signature', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record_wcl', 'person_signature')
    # ### end Alembic commands ###
