"""тестовая миграция

Revision ID: 747da3b542ca
Revises: 
Create Date: 2025-04-10 16:44:42.535604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747da3b542ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('water_consumption_log', 'consumption_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('water_consumption_log', sa.Column('consumption_value', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
