"""обновлено RatesType с расширением до четырех

Revision ID: 3579469a94bc
Revises: aa7205de2e9f
Create Date: 2025-04-26 05:26:34.681687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3579469a94bc'
down_revision: Union[str, None] = 'aa7205de2e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_meter_link', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point_meter_link', 'is_active')
    # ### end Alembic commands ###
