services:
  frontend:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - back_water_net

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - back_water_net

networks:
  back_water_net:
    external: true
    name: back_water_net  # ← Явно указываем ИМЯ сети!
